name: "upload-artifacts"
description: This action used to upload artifacts

inputs:
    shell:
        description: The shell to run the script
        required: true
        default: bash

runs:
    using: "composite"
    steps:
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: ${{ github.ref }}
              release_name: ${{ github.ref }}
              draft: false
              prerelease: false
