name: Electron Playwright Tests

on:
  push:
    branches:
      - e2e/*

env:
  # AWS_S3_BUCKET: "mattermost-cypress-report"
  # JIRA_PROJECT_KEY: 'MM'
  # MM_TEST_SERVER_URL: "http://localhost:8065"
  # ZEPHYR_ENVIRONMENT_NAME: 'Desktop app'
  # ZEPHYR_FOLDER_ID: "3256491"
  # AWS_ACCESS_KEY_ID: ${{ secrets.MM_DESKTOP_E2E_AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.MM_DESKTOP_E2E_AWS_SECRET_ACCESS_KEY }}
  # ZEPHYR_API_KEY: ${{ secrets.MM_DESKTOP_E2E_ZEPHYR_API_KEY }}
  E2E_USER1_PWD: ${{ secrets.E2E_USER1_PWD }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  BRANCH: ${{ github.ref }}
  BUILD_SUFFIX: 'desktop-e2e'
  MM_TEST_SERVER_URL: "https://kchat.infomaniak.com/"
  PULL_REQUEST_BASE_URL: "https://github.com/Infomaniak/kchat-desktop/pull/"
  TYPE: ${{ github.event_name == 'pull_request' && 'PR' || '' }}
  TEST_CYCLE_LINK_PREFIX: ${{ secrets.MM_DESKTOP_E2E_TEST_CYCLE_LINK_PREFIX }}
  WEBHOOK_URL: ${{ secrets.MM_DESKTOP_E2E_WEBHOOK_URL }}


jobs:
  e2e-linux:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
        run: |
          wget -qO - https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04/Release.key | sudo apt-key add -
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 && chmod a+x /usr/local/bin/yq
          sudo apt-get update || true && sudo apt-get install -y ca-certificates libxtst-dev libpng++-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu jq icnsutils graphicsmagick tzdata
          npm ci

      - name: Set Environment Variables
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "BUILD_SUFFIX=desktop-pr" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-release" >> $GITHUB_ENV
            echo "ZEPHYR_ENABLE=false" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-nightly" >> $GITHUB_ENV
          fi
          echo "BUILD_ID=${{ github.run_id }}-${BUILD_SUFFIX}-${{ runner.os }}" >> $GITHUB_ENV
          echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV

          if [ -n "${ZEPHYR_ENABLE}" ]; then
            echo "ZEPHYR_ENABLE=${ZEPHYR_ENABLE}" >> $GITHUB_ENV
          fi

      - name: Run Playwright tests (Ubuntu OS)
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test:e2e || true # making job pass even if the tests fail due to flakyness
          npm run test:e2e:send-report
      - name: ci/upload-report
        uses: actions/upload-artifact@v3
        with:
            name: reports
            path: ./mochawesome-report
            retention-days: 7

  e2e-macos:
    runs-on: macos-12
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20'

      - name: ci/install-dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          brew install yq
          jq '.mac.target=["zip"]' electron-builder.json | jq '.mac.gatekeeperAssess=false' > /tmp/electron-builder.json && cp /tmp/electron-builder.json .
          npm ci

      - name: Set Environment Variables
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-pr" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-release" >> $GITHUB_ENV
            echo "ZEPHYR_ENABLE=false" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-nightly" >> $GITHUB_ENV
          fi
          echo "BUILD_ID=${{ github.run_id }}-${BUILD_SUFFIX}-${{ runner.os }}" >> $GITHUB_ENV
          echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV

          if [ -n "${ZEPHYR_ENABLE}" ]; then
            echo "ZEPHYR_ENABLE=${ZEPHYR_ENABLE}" >> $GITHUB_ENV
          fi

      - name: Run Playwright tests (macOS)
        run: |
          npm run test:e2e || true # making job pass even if the tests fail due to flakyness
          npm run test:e2e:send-report
      - name: ci/upload-report
        uses: actions/upload-artifact@v3
        with:
            name: reports
            path: ./mochawesome-report
            retention-days: 7

  e2e-windows:
    runs-on: windows-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json

      # - name: ci/cache-node-modules
      #   id: cache-node-modules
      #   uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-node-modules
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: ci/install-node-gyp
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          choco install yq --version 4.15.1 -y
          npm i -g node-gyp
          node-gyp install
          node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers"
          node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch arm64
          node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch ia32

      - name: release/install-deps
        shell: powershell
        run: |
            ./scripts/Makefile.ps1 install-deps
            npm ci --openssl_fips=''

      - name: Set Environment Variables
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-pr" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-release" >> $GITHUB_ENV
            echo "ZEPHYR_ENABLE=false" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
            echo "BUILD_SUFFIX=desktop-nightly" >> $GITHUB_ENV
          fi
          echo "BUILD_ID=${{ github.run_id }}-${BUILD_SUFFIX}-${{ runner.os }}" >> $GITHUB_ENV
          echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV

          if [ -n "${ZEPHYR_ENABLE}" ]; then
            echo "ZEPHYR_ENABLE=${ZEPHYR_ENABLE}" >> $GITHUB_ENV
          fi

      - name: Run Playwright tests (Windows OS)
        run: |
          npm run test:e2e || true
          npm run test:e2e:send-report
        shell: bash
      - name: ci/upload-report
        uses: actions/upload-artifact@v3
        with:
            name: reports
            path: ./mochawesome-report
            retention-days: 7
