name: release-windows

on:
    push:
        branches: [feat/github-actions-settings]
        #tags:
        #    - "^[0-9]+.[0-9]+.[0-9]+-(alpha|beta).[0-9]+$"
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: release/checkout-repo
              uses: actions/checkout@v3
            - name: release/setup-node
              uses: actions/setup-node@v3
              with:
                  node-version-file: "package.json"
                  cache: "npm"
                  cache-dependency-path: package-lock.json
            - name: release/optimize
              shell: powershell
              run: ./scripts/Makefile.ps1 optimize
            - name: release/install-deps
              shell: powershell
              run: |
                  ./scripts/Makefile.ps1 install-deps
                  choco install yq --version 4.15.1 -y
                  npm i -g node-gyp
                  node-gyp install
                  node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers"
                  node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch arm64
                  node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch ia32
                  npm ci --openssl_fips=''
            - name: ci/run-i18n-check
              run: |
                  npm run mmjstool -- i18n extract-desktop --desktop-dir .
                  git --no-pager diff --exit-code i18n/en.json
            - name: release/test
              env:
                  ELECTRON_DISABLE_SANDBOX: "1"
              run: npm run test:unit
            - name: release/build
              run: |
                  npm run package:windows-nsis
