name: release-linux

on:
    push:
        branches: [feat/github-actions-settings]
        #tags:
        #    - "[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]"
        #    - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: release/checkout-repo
              uses: actions/checkout@v3
            - name: release/setup-node
              uses: actions/setup-node@v3
              with:
                  node-version-file: "package.json"
                  cache: "npm"
                  cache-dependency-path: package-lock.json
            - name: release/install-dependencies
              run: |
                  wget -qO - https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04/Release.key | sudo apt-key add -
                  wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 && chmod a+x /usr/local/bin/yq
                  sudo apt-get update || true && sudo apt-get install -y ca-certificates libxtst-dev libpng++-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu jq icnsutils graphicsmagick tzdata
                  npm ci
            - name: release/test
              uses: ./.github/actions/test
            - name: release/build
              run: |
                  mkdir -p ./build/linux
                  npm run package:linux
